class AuthenticationError(Exception):
    """Исключение вызывается, когда аутентификация не удалась из-за неверных учетных данных."""
    pass
